# The workbook every example uses.
#
# It is generated by tools/fixtures/make-extdata.R and committed, so these
# assertions are really about the examples: each one exists because some
# documented behaviour depends on it, and an example that quietly stops
# demonstrating what it claims is worse than no example.
#
# Reproducibility of the bytes is checked separately, by running that
# generator with --check; tools/ is not installed, so a test cannot do it.

test_that("the example workbook ships and has both worksheets", {
  path <- system.file("extdata", "two-sheets.xlsx", package = "zuxlsx")
  # Guarding this would hide exactly the failure it needs to report: for a
  # long time this file did not exist, system.file() returned "", and every
  # example in the package silently did nothing.
  expect_true(nzchar(path))
  expect_identical(xlsx_sheets(path), c("readings", "notes"))
})

test_that("the example workbook demonstrates every inferred column type", {
  # read_xlsx()'s documentation describes character, numeric, logical and
  # Date. If the fixture stops covering one of them, the example stops
  # showing what the text promises.
  path <- system.file("extdata", "two-sheets.xlsx", package = "zuxlsx")
  out <- read_xlsx(path)

  expect_named(out, c("station", "reading", "checked", "taken"))
  expect_identical(out$station, c("north", "south", "east"))
  expect_identical(out$reading, c(12.5, 9.75, 14.25))
  expect_identical(out$checked, c(TRUE, FALSE, TRUE))
  expect_s3_class(out$taken, "Date")
  expect_identical(out$taken[1], as.Date("2024-02-02"))
})

test_that("the example workbook uses the 1900 epoch", {
  # The dates above are only right under the 1900 system. Pinned so that a
  # regenerated fixture cannot change epoch without the examples' output
  # changing silently with it.
  path <- system.file("extdata", "two-sheets.xlsx", package = "zuxlsx")
  expect_false(attr(xlsx_cells(path), "date1904"))
})

test_that("the second worksheet carries non-ASCII text", {
  path <- system.file("extdata", "two-sheets.xlsx", package = "zuxlsx")
  notes <- read_xlsx(path, "notes")

  expect_identical(notes$note[2], "µg/m³")
  expect_identical(Encoding(notes$note[2]), "UTF-8")
})

test_that("the range shown in the examples selects what it claims", {
  path <- system.file("extdata", "two-sheets.xlsx", package = "zuxlsx")

  expect_named(read_xlsx(path, range = "B1:C3"), c("reading", "checked"))
  expect_identical(nrow(read_xlsx(path, range = "B1:C3")), 2L)
  expect_named(read_xlsx(path, range = "A2:B4", col_names = FALSE), c("X1", "X2"))
})
